### ISSUE TITLE
redpanda: even smaller footprint

### ISSUE THREAD

**Issue by emaxerrno** [floodplainio/floodplain-library#14]
Hi all, i saw this really cool project when i was messing around. one of the redpanda devs here. 

i noticed you are running redpanda for instances, and figured i can suggest how to run redpanda with an even smaller footprint for the unit tests 

https://vectorized.io/docs/docker-compose/

here is an example

```yaml


version: '3.7'
services:
  redpanda:
    entrypoint:
    - /usr/bin/rpk
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --set
    - "redpanda.enable_transactions=true"
    - --set
    - "redpanda.enable_idempotence=true"
    # NOTE: Please use the latest version here!
    image: vectorized/redpanda:v21.6.2
    ports:
    - 9092:9092
    - 29092:29092
    volumes:
    - redpanda:/var/lib/redpanda/data
volumes:
  redpanda: null

```

in any case, i would also recommend pinning the version of redpanda instead of lateast. 

Let me know if I could help in anyway. (feel free to ping me in our slack as well, either works)
